### ISSUE TITLE
kubernetes补丁版本升级方式有误

### ISSUE THREAD

**Issue by weilinqwe** [cnrancher/docs-rancher2#187]
系统管理员指南->获取新的kubernetes版本里写到：
要升级补丁版本，只需refresh rke-metadata-config，然后：
1. 转到全局视图并单击系统设置选项卡。
2. 转到rke-metadata-config部分。单击省略号(…)并单击升级

这里是没有升级按钮的。

正确方式应该是：进入具体的集群编辑页面，然后选择新的版本，点击保存会自动更新。

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/81262662-cd1a2100-9070-11ea-8c1d-7991fcfd3881.png)

有的

这个文档是说在不升级rancher的情况下，获取新版本的kubernetes

比如rancher版本发布时，rancher只支持1.17.3

等有一天rancher 发布了 1.17.4 后，可以在不升级rancher版本的情况下，通过这个方法获取到1.17.4的版本信息。

然后你的业务集群就可以在编辑集群页面看到1.17.4了

**Comment by weilinqwe** [comment]
我看了一下，换了中文进去，变成升级了，英文版里还是edit。 点击这个还是修改参数（刷新间隔和刷新url），难道保存了之后就能自动升级？

**Comment by loganhz** [comment]
rancher 会定期按照你配置的地址定期获取k8s元数据。一般你不用自己改，等rancher真的更新了元数据，rancher server会自动获取，然后你就能在ui上看到新版本了。升级集群还得你自己手动去编辑集群页面升级

**Comment by weilinqwe** [comment]
对，所以这个升级的描述有误导。其实就是编辑，还是英文比较正确。  建议一下。

**Comment by loganhz** [comment]
是的 这个是产品的翻译有问题。我看看要不要改一下 把升级改成编辑

**Comment by loganhz** [comment]
类型issue应该提到 rancher/rancher 因为要改的是产品代码，不是文档
