### ISSUE TITLE
基于rancher二次开发翻译

### ISSUE THREAD

**Issue by wdt1988520** [cnrancher/docs-rancher2#285]
二次开发指南有翻译文档吗？

**Comment by loganhz** [comment]
如果需求不是很复杂 基于Rancher API 重写一下Rancher UI就可以了

建议结合chrome network，Rancher API UI ，Rancher UI 源代码，再结合UI点击，可以查看相关的数据和请求。

如果需求很复杂，需要改rancher后端的代码，就要先学习golang, 目前可以参考的wiki 在这里 https://github.com/rancher/rancher/wiki
