### ISSUE TITLE
preview分支build失败

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/docs-rancher2#426]
12.16.0: Pulling from library/node
--
2 | Digest: sha256:454651174f54836571258a329788574cf6552bddfd1a7113e769bd9fc3776fe6
3 | Status: Downloaded newer image for node:12.16.0
4 | + yarn install
5 | yarn install v1.22.0
6 | [1/4] Resolving packages...
7 | [2/4] Fetching packages...
8 | info fsevents@2.1.2: The platform "linux" is incompatible with this module.
9 | info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
10 | info fsevents@1.2.12: The platform "linux" is incompatible with this module.
11 | info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
12 | [3/4] Linking dependencies...
13 | warning " > @docusaurus/plugin-baidu-analytics@1.0.0-alpha2" has incorrect peer dependency "@docusaurus/core@^2.0.0".
14 | warning " > @docusaurus/preset-classic@2.0.0-alpha.50" has incorrect peer dependency "@docusaurus/core@^2.0.0".
15 | warning "@docusaurus/preset-classic > @docusaurus/plugin-content-blog@2.0.0-alpha.50" has incorrect peer dependency "@docusaurus/core@^2.0.0".
16 | warning "@docusaurus/preset-classic > @docusaurus/plugin-content-docs@2.0.0-alpha.50" has incorrect peer dependency "@docusaurus/core@^2.0.0".
17 | warning "@docusaurus/preset-classic > @docusaurus/plugin-content-pages@2.0.0-alpha.50" has incorrect peer dependency "@docusaurus/core@^2.0.0".
18 | warning "@docusaurus/preset-classic > @docusaurus/plugin-google-analytics@2.0.0-alpha.50" has incorrect peer dependency "@docusaurus/core@^2.0.0".
19 | warning "@docusaurus/preset-classic > @docusaurus/plugin-google-gtag@2.0.0-alpha.50" has incorrect peer dependency "@docusaurus/core@^2.0.0".
20 | warning "@docusaurus/preset-classic > @docusaurus/plugin-sitemap@2.0.0-alpha.50" has incorrect peer dependency "@docusaurus/core@^2.0.0".
21 | warning "@docusaurus/preset-classic > @docusaurus/theme-classic@2.0.0-alpha.50" has incorrect peer dependency "@docusaurus/core@^2.0.0".
22 | warning "@docusaurus/preset-classic > @docusaurus/theme-classic@2.0.0-alpha.50" has unmet peer dependency "webpack@^4.41.2".
23 | warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia@2.0.0-alpha.50" has incorrect peer dependency "@docusaurus/core@^2.0.0".
24 | warning "@docusaurus/preset-classic > @docusaurus/theme-classic > react-toggle@4.1.1" has unmet peer dependency "prop-types@^15.3.0 \|\| ^16.0.0".
25 | [4/4] Building fresh packages...
26 | Done in 87.36s.
27 | + yarn build
28 | yarn run v1.22.0
29 | $ docusaurus build
30 | Creating an optimized production build...
31 | [info] [webpackbar] Compiling Client
32 | [info] [webpackbar] Compiling Server
33 | Browserslist: caniuse-lite is outdated. Please run:
34 | npx browserslist@latest --update-db
35 | [success] [webpackbar] Client: Compiled successfully in 1.56m
36 | [success] [webpackbar] Server: Compiled with some errors in 1.96m
37 |  
38 |  
39 | ReferenceError: mode is not defined
40 | (undefined) ReferenceError: mode is not defined
41 | at MDXContent (main:44554:8626)
42 | at d (main:58086:498)
43 | at $a (main:58089:16)
44 | at a.b.render (main:58094:476)
45 | at a.b.read (main:58094:18)
46 | at Object.renderToString (main:58104:364)
47 | at render (main:85953:252)
48 | at runNextTicks (internal/process/task_queues.js:62:5)
49 | at processTimers (internal/timers.js:489:9)
50 | Error: Failed to compile with errors.
51 | at /drone/src/node_modules/@docusaurus/core/lib/commands/build.js:37:24
52 | at finalCallback (/drone/src/node_modules/webpack/lib/MultiCompiler.js:254:12)
53 | at /drone/src/node_modules/webpack/lib/MultiCompiler.js:277:6
54 | at done (/drone/src/node_modules/neo-async/async.js:2931:13)
55 | at runCompilers (/drone/src/node_modules/webpack/lib/MultiCompiler.js:181:48)
56 | at /drone/src/node_modules/webpack/lib/MultiCompiler.js:188:7
57 | at /drone/src/node_modules/webpack/lib/MultiCompiler.js:270:7
58 | at finalCallback (/drone/src/node_modules/webpack/lib/Compiler.js:257:39)
59 | at /drone/src/node_modules/webpack/lib/Compiler.js:273:13
60 | at AsyncSeriesHook.eval [as callAsync] (eval at create (/drone/src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:40:1)
61 | at AsyncSeriesHook.lazyCompileHook (/drone/src/node_modules/tapable/lib/Hook.js:154:20)
62 | at onCompiled (/drone/src/node_modules/webpack/lib/Compiler.js:271:21)
63 | at /drone/src/node_modules/webpack/lib/Compiler.js:681:15
64 | at AsyncSeriesHook.eval [as callAsync] (eval at create (/drone/src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
65 | at AsyncSeriesHook.lazyCompileHook (/drone/src/node_modules/tapable/lib/Hook.js:154:20)
66 | at /drone/src/node_modules/webpack/lib/Compiler.js:678:31
67 | error Command failed with exit code 1.
68 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kingsd041** [comment]
报错原因：
monitoring-alerting/v2.0.x-v2.4.x/cluster-alerts/_index.md 中包含的```sum(node_load5) / count(node_cpu_seconds_total{mode="system"})```导致的报错

解决办法：
删除该页面所有的`<br/>`选项

**Comment by yzeng25** [comment]
这是构建失败的其中一种情况，我会把近期碰到的构建失败情况和对应的解决方法整理出来放到wiki里面，预计四月份会做完

**Comment by yzeng25** [comment]
归纳的详情请参考下文：
https://github.com/cnrancher/docs-rancher2/wiki/master%E5%88%86%E6%94%AF%E5%92%8Cpreview%E5%88%86%E6%94%AF%E6%9E%84%E5%BB%BA%E5%A4%B1%E8%B4%A5%E8%AF%A6%E8%A7%A3
