### ISSUE TITLE
中文文档和英文文档的backup目录下的文件夹对不上

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/docs-rancher2#434]
中文文档和英文文档的backup目录下的文件夹对不上：
![image](https://user-images.githubusercontent.com/19684717/100839273-e96b2880-34ae-11eb-98ca-0ddb3c14f0b2.png)

![image](https://user-images.githubusercontent.com/19684717/100839281-ee2fdc80-34ae-11eb-946b-9716b862d528.png)

**Comment by yzeng25** [comment]
这个我认为不是问题，原因如下：
1. rancher单节点备份和恢复两篇文档的内容与英文docker备份和恢复文档相同，只是链接不一样。
2. 链接和导航栏不影响阅读体验，主要是英文文档的链接改了，其实我这边也可以把对应的链接、标题改掉，但是改完的效果也就是标题和导航栏有变化，文章内容是一模一样的。
ref：
1. rancher单节点备份：https://docs.rancher.cn/docs/rancher2/backups/2.0-2.4/single-node-backups/_index
2. docker backups（与1对应）：https://rancher.com/docs/rancher/v2.x/en/backups/v2.0.x-v2.4.x/backup/docker-backups/
3. rancher单节点恢复：http://localhost:3000/docs/rancher2/backups/2.0-2.4/restorations/single-node-restoration/_index
4. docker restore（与3对应）：https://rancher.com/docs/rancher/v2.x/en/backups/v2.0.x-v2.4.x/restore/docker-restores/
