### ISSUE TITLE
清理脚本少清理了/usr/libexec/kubernetes目录

### ISSUE THREAD

**Issue by yl-yue** [cnrancher/docs-rancher2#468]
清理脚本少清理了`/usr/libexec/kubernetes`目录，导致Unable to update cni config: no networks found in /etc/cni/net.d

**Comment by yzeng25** [comment]
已合入，请联系rancher小助手，加入社区用户群并领取奖励。

**Comment by yzeng25** [comment]
已合入，请联系rancher小助手，加入社区用户群并领取奖励。
