### ISSUE TITLE
官网快速启动命令缺少--privileged

### ISSUE THREAD

**Issue by silenceGuo** [cnrancher/docs-rancher2#478]
**问题描述**
官网https://www.rancher.cn/quick-start/ 这里快速通过命令启动rancher，会无法启动 需要增加参数 --privileged

**问题类型**
请选择一个最符合的选项：1

1. 缺少对应描述
2. 描述不准确
3. 错别字/用词错误
4. 链接跳转失败，单击该链接返回404
5. 图片挂了
6. 文档架构不合理，有些文档层级太深了，不好找
7. 使用页面右上方的搜索框没找到想找的东西
8. 其他问题（请详细说明）

**现网文档URL**

请输入文档页面的URL，利于快速发现和解决问题。

**文档网页截图截图**
请提供截图，利于快速定位和解决问题
![image](https://user-images.githubusercontent.com/28891624/102981586-22de0380-4544-11eb-890f-da8b433523bb.png)
![image](https://user-images.githubusercontent.com/28891624/102981609-2d989880-4544-11eb-9483-1a42cc8d0685.png)

**修改建议**
请说明您对这个问题的修改意见或建议，从用户的角度出发，您觉得应该怎么改。

**其他备注或说明（可选）**

**Comment by yzeng25** [comment]
文档内的相关描述已更新，官网上面的描述可能得晚点更新。感谢老哥提issue。
https://github.com/cnrancher/docs-rancher2/pull/481

**Comment by yzeng25** [comment]
官网页面已更新，关闭问题单。
![image](https://user-images.githubusercontent.com/36651058/102986157-553f2f00-454b-11eb-8211-c61761f26fe4.png)
