### ISSUE TITLE
创建阿里云ACK集群,无法获取vpc，sw

### ISSUE THREAD

**Issue by silenceGuo** [cnrancher/docs-rancher2#487]
**问题描述**
通过docker快速启动rancher2.5.3，在创建阿里云ack时无法获取vpc
在未选择vpc等必选项时，点击下一步，一直在加载
**问题类型**
请选择一个最符合的选项：

8. 其他问题（请详细说明）

**现网文档URL**

请输入文档页面的URL，利于快速发现和解决问题。

**文档网页截图截图**
![image](https://user-images.githubusercontent.com/28891624/103129257-1340f500-46d3-11eb-846c-91c64b8ac2a1.png)
![image](https://user-images.githubusercontent.com/28891624/103129338-57cc9080-46d3-11eb-90e2-33a1bf62f681.png)

**修改建议**
请说明您对这个问题的修改意见或建议，从用户的角度出发，您觉得应该怎么改。

**其他备注或说明（可选）**

**Comment by yzeng25** [comment]
@silenceGuo 老哥您这个确定是文档的问题而不是UI‘的问题吗？

**Comment by kingsd041** [comment]
@silenceGuo  先选择 交换机，然后再选择 专有网络 试试

**Comment by yzeng25** [comment]
@silenceGuo 老哥试了吗？

**Comment by silenceGuo** [comment]
么有，把rancher当看板再用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cnrancher/docs-rancher2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月23日(星期三) 下午2:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cnrancher/docs-rancher2] 创建阿里云ACK集群,无法获取vpc，sw (#487)





 
@silenceGuo 老哥试了吗？

**Comment by yzeng25** [comment]
@silenceGuo 如果不影响使用的话，我就先关单了嗷

**Comment by silenceGuo** [comment]
好的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cnrancher/docs-rancher2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月23日(星期三) 下午3:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cnrancher/docs-rancher2] 创建阿里云ACK集群,无法获取vpc，sw (#487)





 
@silenceGuo 如果不影响使用的话，我就先关单了嗷
