### ISSUE TITLE
Rancher阿里云镜像仓库镜像版本与dockerhub版本差异过大

### ISSUE THREAD

**Issue by yl-yue** [cnrancher/docs-rancher2#501]
**问题描述**
Rancher阿里云镜像仓库镜像版本与dockerhub版本差异过大，如：[rancher/fleet-agent](https://hub.docker.com/r/rancher/fleet-agent/tags?page=1&ordering=last_updated) 镜像，截止今日2021-1-18最新 `rancher/fleet-agent:v0.3.3` 已于6天前发布，而阿里云镜像仓库最新版本任然为`rancher/fleet-agent:v0.3.2` .

**问题类型**
请选择一个最符合的选项：

8. 其他问题（请详细说明）

**现网文档URL**
https://docs.rancher.cn/docs/rancher2/best-practices/2.0-2.4/use-in-china/_index#使用阿里云镜像仓库搭建-rancher

**文档网页截图截图**
![image](https://user-images.githubusercontent.com/39790401/104887789-dc46c200-59a6-11eb-9b20-917311c89596.png)

**修改建议**
目前也没有办法，帮助官网同步最新镜像，导致镜像拉取失败，集群起不起来。是否可以探寻一个较为友好的方式，开发者也可以同步镜像

**Comment by kingsd041** [comment]
你是安装哪个版本的rancher用到了 fleet-agent:v0.3.2 ?

**Comment by yl-yue** [comment]
rancher/fleet-agent:v0.3.3

Rancher:v2.5.5

**Comment by kingsd041** [comment]
Rancher 2.5.5依赖的是 `rancher/fleet-agent:v0.3.2`，我是直接到rancher/rancher [v2.5.5 release](https://github.com/rancher/rancher/releases/tag/v2.5.5)里的rancher-images.txt里查看的。
![image](https://user-images.githubusercontent.com/19684717/104898731-f4bdd900-59b4-11eb-93e6-542ba2b5efbb.png)

**Comment by yl-yue** [comment]
![image](https://user-images.githubusercontent.com/39790401/104909635-1c1ba280-59c3-11eb-8d4e-8ed6a0a87a56.png)
![image](https://user-images.githubusercontent.com/39790401/104909645-2047c000-59c3-11eb-9314-834c09fdedaf.png)

**Comment by kingsd041** [comment]
已经修复
