### ISSUE TITLE
https://docs.rancher.cn/docs/k3s/helm/_index  文章内链接错误

### ISSUE THREAD

**Issue by east4ming** [cnrancher/docs-rancher2#701]
**问题描述**
https://docs.rancher.cn/docs/k3s/helm/_index  文章内链接错误
**问题类型**
请选择一个最符合的选项：

4. 链接跳转错误

**现网文档URL**

https://docs.rancher.cn/docs/k3s/helm/_index 

**文档网页截图截图**
![image](https://user-images.githubusercontent.com/13358726/150055400-eb22b04c-462c-4d0d-9809-52f81661ec16.png)

**修改建议**
请说明您对这个问题的修改意见或建议，从用户的角度出发，您觉得应该怎么改。

**其他备注或说明（可选）**

**Comment by kingsd041** [comment]
我这没问题啊，要不你清理缓存再试试？

![image](https://user-images.githubusercontent.com/19684717/150452643-f3d7839e-b786-490f-aa20-3a60bbf81067.png)
