### ISSUE TITLE
用词错误

### ISSUE THREAD

**Issue by wangzheyuan** [cnrancher/docs-rancher2#720]
**问题描述**
文档用词错误

**现网文档URL**
https://docs.rancher.cn/docs/rke2/install/airgap/_index#%E5%AE%89%E8%A3%85-rke2

**文档网页截图截图**
![20220214155131](https://user-images.githubusercontent.com/23622441/153822207-3db815a4-933e-48b8-9115-c2658111ea8f.png)

**修改建议**
将私有注册表方法修改为私有镜像仓库方式。

**Comment by kingsd041** [comment]
@vickyhella  ^^
