### ISSUE TITLE
连接错误

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/docs-rancher2#739]
**问题描述**
请使用一到两句话概述这个问题
`具体要求` 连接到了 2.4 的文档

http://docs.rancher.cn/docs/rancher2.5/quick-start-guide/deployment/quickstart-manual-setup/_index

<img width="885" alt="image" src="https://user-images.githubusercontent.com/19684717/155049411-ed43b991-13ff-4b4f-9666-0fab24b7d874.png">

**Comment by vickyhella3** [comment]
issue resolved
