### ISSUE TITLE
中文文档 2.5 和 2.4  首页的版本说明未更新，现在显示错误的最新版本

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/docs-rancher2#767]
中文文档 2.5 和 2.4  首页的版本说明未更新，现在显示错误的最新版本

连接：
https://docs.rancher.cn/rancher2/
https://docs.rancher.cn/rancher2.5/

截图：
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/19684717/177072827-a3e16d2f-037d-4c07-9578-7709c5d4d67d.png">

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/19684717/177072848-70108e4a-5bd9-4a96-90a8-08cf48829f06.png">

**Comment by vickyhella** [comment]
This issue has been fixed.
