### ISSUE TITLE
离线部署的2.4与2.5的区别这里迷惑

### ISSUE THREAD

**Issue by zszen** [cnrancher/docs-rancher2#783]
**问题描述**
2.4启动参数
`docker run -d --privileged --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:latest`
2.5启动参数
`docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:latest`

然后描述是这么说的：`与 2.4.x 或之前的版本相比，使用docker run命令安装 Rancher 2.5.x 时，需要添加--privileged标志变量，启用特权模式安装 Rancher。`

这两个命令分明就是参数位置变了而已嘛

**Comment by kingsd041** [comment]
不好意思，应该是 2.4 的稳定里多了个  `--privileged` 参数，之前批量替换的时候出现了问题

@vickyhella  请把 2.4 文档中的  `--privileged` 参数去掉，2.5 中不变
