### ISSUE TITLE
faq 图片 403，无法查看

### ISSUE THREAD

**Issue by 117503445** [cnrancher/docs-rancher2#803]
**问题描述**
[faq](https://docs.rancher.cn/docs/k3s/faq/_index) 图片 403，无法查看

**问题类型**
请选择一个最符合的选项：

5. 图片挂了

**现网文档URL**

<https://docs.rancher.cn/docs/k3s/faq/_index>

**文档网页截图截图**
![image](https://user-images.githubusercontent.com/21152034/213348860-59d4f018-ba8e-436c-a9a3-2f0af4740836.png)

**修改建议**
修复图片问题

**Comment by vickyhella** [comment]
@117503445 感谢提交 issue。请知悉，K3s 的中英文文档现已统一到 https://docs.k3s.io/ 站点（中文文档：https://docs.k3s.io/zh/ ）。我们现已不再维护 https://docs.rancher.cn 中的 K3s 文档。请前往新站点进行访问~

**Comment by 117503445** [comment]
好的，谢了
